### ISSUE TITLE
##爱课程错误

### ISSUE THREAD

**Issue by zychen2016** [Foair/course-crawler#13]
## （错误简述）

网站：爱课程

课程地址：http://www.icourses.cn/sCourse/course_3220.html

问题描述：1、此课程没有找到你说明中给出的视频地址格式；
                   2、PDF、PPT文件是否可以下载？

（请将相关内容替换，按照格式填写 issue，方便我快速找到错误）

**Comment by Foair** [comment]
抱歉，是我没有写清楚。

我也是刚刚才知道有「资源共享课」，起初我以为只有「视频公开课」。

目前的话呢，只能下载视频公开课。

资源共享课的部分会在以后添加。谢谢反馈。
