### ISSUE TITLE
网易云课堂 MOOC下不了？

### ISSUE THREAD

**Issue by SigureMo** [Foair/course-crawler#14]
### 网易云课堂 MOOC

1. 网站：网易云课堂 MOOC

2. 课程地址：突然都不能下载了，比如：https://mooc.study.163.com/course/2001281002#/info

3. 问题描述：有木有收到邮件呀，那里有详细描述

**Comment by Foair** [comment]
问题解决了，将 HTTP 替换为 HTTPS 即可。谢谢反馈。

邮件的内容我当天就留意到了，只是最近几天比较忙，稍后会回复你的。 😄

**Comment by SigureMo** [comment]
哇真的可以了！太感谢了！其实本来也不急，只是过两天就不在家了想提前下点视频嘿嘿
我把study_163也修改了，改了挺多的，测试了三门课是可以正常用的，具体代码和改动看我fork的分支吧
1. 取消cookies（其实是加了cookies就莫名其妙SessionError）
2. 另外发现每个lesson有多种type 2是视频 3是pdf 就取消了原来傻傻的根据ref的扩展名进行分流的想法，ref就放在Files里面了
3. 修改视频解析过程，突然发现原来的不适用了（完全忘了原来的为啥能成功），就改成了从json里获取
4. 可能有字幕，接口应该在返回的json里，但暂时没发现这样的课（那个吴恩达的居然视频里直接合成了字幕）
先去下视频了嘿嘿，不用回我了
