### ISSUE TITLE
网易云课堂课程，下载得到的附件压缩包(主要是代码文件)显示损坏无法打开

### ISSUE THREAD

**Issue by tanjiarui15** [Foair/course-crawler#17]
## （错误简述）

网站：网易云课堂 MOOC

课程地址：https://mooc.study.163.com/learn/1000013001?tid=2001493000

问题描述：下载课程附件（主要是代码压缩包），显示压缩包损坏无法打开

**Comment by SigureMo** [comment]
全部这样吗？删掉重试呢？

**Comment by SigureMo** [comment]
有空加个Debug文件吧 @Foair  把网址等信息，都记录下来，他这个还真不好测试……

**Comment by tanjiarui15** [comment]
<html>
<head>
</head>
<body>
<script>
window.open("https://www.icourse163.org/course/attachment.htm?nosKey=970E89E9A7FD4BCECA750BB6CC1E99B6-1472021484929&fileName=HttpDemoAndPPT.zip",'_self');
</script>
</body>
</html>

这个是用notepad++打开后显示的

**Comment by SigureMo** [comment]
喵？Σ(⊙▽⊙"a我直接用requests测试是可以下的，那个文件修改扩展名为HTML后打开也是自动跳转下载的，emmmmmmm不资到为撒能把那个页面download下来

**Comment by SigureMo** [comment]
问题在我的课程[C++程序设计入门(下)](https://mooc.study.163.com/learn/1000005002?tid=2001529012#/learn/content?type=detail&id=2001831579&cid=2001840499)重现  
解决方法：
经测试，使用session的CANDY对课件进行下载将会重定向到一个页面后使用js进行下载，而直接使用requests则会直接下载内容，故可以直接对使用requests下载或者使用参数将session注释掉，两者选择其一即可
1. 
```Python
file_name = '%s %s' % (counter, file_name) # 下面是要修改的内容
with open(WORK_DIR.file(file_name), 'wb') as f:
    r = requests.get('https://www.icourse163.org/course/attachment.htm', params=params)
    f.write(r.content)
```
2. 
```Python
file_name = '%s %s' % (counter, file_name) # 下面是要修改的内容
CANDY.download_bin('https://www.icourse163.org/course/attachment.htm',
                                    WORK_DIR.file(file_name), params=params, cookies={'STUDY_SESS': None})
```

位置在study_mooc.py 177行左右
