### ISSUE TITLE
请问是否可以下载网易云课堂 MOOC 的“已关闭课程”？

### ISSUE THREAD

**Issue by hmgqzx** [Foair/course-crawler#8]
## 是否可以下载“已关闭课程”？

网站：网易云课堂 MOOC

问题描述：作者，你好，非常感谢你的劳动。我现在还未使用过，想问下在其他开课课程页面拿到 cookie 后，是否能用于“已关闭课程”的下载呢？

**Comment by Foair** [comment]
对于网易云课堂的 MOOC 课程来说，只要是在网页上可以进入的课程就可以下载，不能进入（没有报名、已关闭）的课程暂时没有方法下载。网易云课堂会真正进行验证，所以没有办法。
