### ISSUE TITLE
输入地址有误

### ISSUE THREAD

**Issue by usernameisalreadytakentoo** [Foair/course-crawler#9]
网站：网易云课堂 MOOC
课程地址：http://study.163.com/course/courseMain.htm?courseId=1003629025
问题描述：使用 python mooc.py http://study.163.com/course/courseMain.htm?courseId=1003629025
的时候，返回输入地址有误
这个链接指的就是您说的那个普通的网易云课堂吗？
————————————————————————
感谢您写的代码，实在是太方便了，我用来下mooc的解剖视频没有问题。

**Comment by Foair** [comment]
无法获取网易云课堂的普通课程，即 `study.163.com` 这个域名下的课程。只适用于 `mooc.study.163.com` 域下的课程。

详细请看 https://mooc.xoy.io/#/specific/study-163-mooc

**Comment by usernameisalreadytakentoo** [comment]
感谢您的回复，了解了
